spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/bulletchat?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/Los_Angeles&allowPublicKeyRetrieval=True
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  redis:
    data:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

  kafka:
    bootstrap-servers: ${kafka.servers}
    consumer:
      group-id: ${kafka.group}
      auto-offset-reset: ${kafka.auto-offset-reset}

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

db:
  host: localhost
  port: 3306
  username: root
  password: Celtics119.

redis:
  host: 127.0.0.1
  port: 6379
  password:

kafka:
  servers: localhost:9092
  group: bullet-chat
  auto-offset-rest: earliest

---
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

db:
  host:
  port:
  username:
  password: